#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

tag="$(date -u +%Y%m%dT%H%M%SZ)"

docker build --pull . -t baelish/dhcpd:latest
docker tag baelish/dhcpd:latest baelish/dhcpd:"$tag"

docker push baelish/dhcpd:latest
docker push baelish/dhcpd:"$tag"

