#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

tag="$(date -u +%Y%m%dT%H%M%SZ)"

docker build --pull . -t baelish/caching-dns:latest
docker tag baelish/caching-dns:latest baelish/caching-dns:"$tag"

docker push baelish/caching-dns:latest
docker push baelish/caching-dns:"$tag"

