#!/bin/sh

pid=0

runApp() {
    updateApp
    cd /service || exit 1
    svscan &
    pid=${!}
    wait $pid
}


# Terminate Application.
terminateApp() {
    if [ $pid -ne 0 ]; then
        kill -SIGTERM "$pid"
    fi
}

# Update Application
updateApp(){
    for dir in env root/ip root/servers; do
      if [ -d "/data/${dir#root/}" ] && [ -n "$(ls "/data/${dir#root}")" ]; then
        cp -v "/data/${dir#root/}/"* "/etc/dnscache/$dir/"
      fi
    done
}

# When SIGTERM is sent, terminate Application.
trap 'terminateApp' TERM

ln -s /etc/dnscache /service/
runApp
