#!/bin/sh

pid=0

runApp() {
    updateApp
    cd /service
    svscan &
    pid=${!}
    wait $pid
}


# Terminate Application.
terminateApp() {
    if [ $pid -ne 0 ]; then
        kill -SIGTERM "$pid"
    fi
}

# Update Application
updateApp(){
    cp /data/env/* /etc/dnscache/env/
    cp /data/ip/* /etc/dnscache/root/ip/
    cp /data/servers/* /etc/dnscache/root/servers/
}

# When SIGTERM is sent, terminate Application.
trap 'terminateApp' SIGTERM

ln -s /etc/dnscache /service/
runApp
